# /// script
# requires-python = "==3.12.*"
# dependencies = [
#   "numpy==2.3.3",
#   "statsmodels==0.14.5",
# ]
# ///
"""Reference generator for MAT_COVARIANCE (U16 E1-S2).

Writes ../../matrix_reference_values_test.go (package service): the
fixture rows and, per (weight column, ddof), the covariance matrix and
its determinant the external references compute. CI never runs Python;
the Go literals ARE the pinned oracle. Never hand-edit the output.

Regenerate:

    cd internal/service/testdata/matrix_reference
    uv run --no-project gen_matrix_reference.py
    gofmt -w ../../matrix_reference_values_test.go

References, and how each maps onto Pulse's definition (listwise: a row
with any member null is dropped; Cov = M2_w / (Σw − ddof)):

  * unweighted — numpy.cov(rows, rowvar=False, ddof=ddof) on the
    listwise-complete rows.
  * frequency weights f — statsmodels DescrStatsW(rows, weights=f,
    ddof=ddof).cov, cross-checked against numpy.cov(fweights=f).
  * probability weights p — DescrStatsW(rows, weights=p, ddof=ddof).cov
    (statsmodels divides by sum_weights − ddof, Pulse's denominator).
  * determinant — numpy.linalg.det of the reference covariance.

A row of weight 0 is kept (it counts toward n and adds no mass, which
neither reference distinguishes from dropping it).
"""

import pathlib

import numpy as np
from statsmodels.stats.weightstats import DescrStatsW

NULL = None
# x1, x2, x3, f (frequency), p (probability)
ROWS = [
    (2.5, 10.0, 1.0, 1, 0.50),
    (3.1, 12.5, 0.0, 2, 1.25),
    (NULL, 9.0, 1.0, 1, 0.75),
    (4.7, 15.25, 1.0, 3, 2.00),
    (1.2, 7.5, 0.0, 1, 0.30),
    (5.9, NULL, 1.0, 2, 1.10),
    (3.3, 11.0, 0.0, 0, 0.00),
    (6.4, 19.75, 1.0, 1, 0.90),
    (2.0, 8.25, 0.0, 4, 1.60),
    (4.1, 13.5, NULL, 1, 0.45),
    (3.8, 12.0, 1.0, 2, 1.35),
    (0.9, 6.0, 0.0, 1, 0.20),
]

complete = [r for r in ROWS if None not in r[:3]]
X = np.array([r[:3] for r in complete], dtype=float)
F = np.array([r[3] for r in complete], dtype=float)
P = np.array([r[4] for r in complete], dtype=float)


def cov(weight, ddof):
    if weight is None:
        return np.cov(X, rowvar=False, ddof=ddof)
    w = F if weight == "f" else P
    c = DescrStatsW(X, weights=w, ddof=ddof).cov
    if weight == "f":
        ref = np.cov(X, rowvar=False, ddof=ddof, fweights=F.astype(int))
        assert np.allclose(c, ref, rtol=1e-13, atol=0), (c, ref)
    return c


def lit(v):
    if v is None:
        return "math.NaN()"
    return repr(float(v))


out = []
out.append("// Code generated by testdata/matrix_reference/gen_matrix_reference.py; DO NOT EDIT.\n")
out.append("// numpy " + np.__version__ + ", statsmodels DescrStatsW.\n\n")
out.append("package service\n\nimport \"math\"\n\n")
out.append("// matrixRefRows are x1, x2, x3, f (frequency weight), p (probability\n// weight); NaN is a null cell.\n")
out.append("var matrixRefRows = [][5]float64{\n")
for r in ROWS:
    out.append("\t{" + ", ".join(lit(v) for v in r) + "},\n")
out.append("}\n\n")
out.append("// matrixRefCases: weight column (\"\" = unweighted), ddof, covariance, determinant.\n")
out.append("var matrixRefCases = []struct {\n\tweight string\n\tddof   int\n\tcov    [3][3]float64\n\tdet    float64\n}{\n")
for weight in (None, "f", "p"):
    for ddof in (0, 1):
        c = cov(weight, ddof)
        det = np.linalg.det(c)
        rows = ", ".join("{" + ", ".join(repr(float(v)) for v in row) + "}" for row in c)
        out.append("\t{%s, %d, [3][3]float64{%s}, %r},\n" % ('"' + (weight or "") + '"', ddof, rows, float(det)))
out.append("}\n")

dest = pathlib.Path(__file__).resolve().parent.parent.parent / "matrix_reference_values_test.go"
dest.write_text("".join(out))
print("wrote", dest)
