package io

import (
	"strings"
	"testing"

	"github.com/frankbardon/pulse/encoding"
)

// pipeSetSamples constructs minSampleRows rows where the "issuers"
// column carries 2 pipe-delimited tokens per cell — every cell hits
// the heuristic. Other columns stay scalar so the heuristic does not
// fire on them.
func pipeSetSamples() *mockReader {
	rows := make([][]string, 0, minSampleRows)
	pairs := []string{"VISA|MC", "AMEX|DISC", "VISA|AMEX", "MC|DISC"}
	categories := []string{"A", "B", "C"}
	for i := 0; i < minSampleRows; i++ {
		// id column repeats (categorical) — so the "all unique
		// cells" guard does not fire on it.
		rows = append(rows, []string{
			categories[i%len(categories)],
			pairs[i%len(pairs)],
		})
	}
	return newMockReader([]string{"id", "issuers"}, rows)
}

func itoa(i int) string {
	if i == 0 {
		return "0"
	}
	var buf [20]byte
	pos := len(buf)
	for i > 0 {
		pos--
		buf[pos] = byte('0' + i%10)
		i /= 10
	}
	return string(buf[pos:])
}

func TestInfer_SetFromPipeDelimitedCSV(t *testing.T) {
	r := pipeSetSamples()
	res, err := InferSchemaWithOptions(r, InferOptions{})
	if err != nil {
		t.Fatalf("InferSchemaWithOptions: %v", err)
	}
	if got := res.Schema.Field("issuers").Type; got != encoding.FieldTypeSetU8 {
		t.Errorf("issuers type = %s, want set_u8", got)
	}
	if d := res.Delimiters["issuers"]; d != "|" {
		t.Errorf("delimiter = %q, want |", d)
	}
}

func TestInfer_SetRespectsMinPct(t *testing.T) {
	// Build a 60-row sample where only 5 rows carry the pipe — far
	// below the default 30% threshold; heuristic must not fire.
	rows := make([][]string, 0, 60)
	for i := 0; i < 5; i++ {
		rows = append(rows, []string{itoa(i), "VISA|MC"})
	}
	for i := 5; i < 60; i++ {
		rows = append(rows, []string{itoa(i), "VISA"})
	}
	r := newMockReader([]string{"id", "issuers"}, rows)
	res, err := InferSchemaWithOptions(r, InferOptions{})
	if err != nil {
		t.Fatalf("InferSchemaWithOptions: %v", err)
	}
	got := res.Schema.Field("issuers").Type
	if got.IsSet() {
		t.Errorf("low-frequency delimiter wrongly classified as %s; want categorical_*", got)
	}
}

func TestInfer_SetOverflowFallsBackToCategorical(t *testing.T) {
	// Build a column with many pipe-delimited cells whose post-split
	// unique-token count exceeds set_u64 capacity (64). The set
	// probe rejects on cardinality; the categorical fallback then
	// accepts because the cells themselves repeat enough to avoid
	// the unbounded guard. 200 rows × 35 distinct cells (each
	// "TX|TY" for 70 unique tokens).
	rows := make([][]string, 0, 200)
	categories := []string{"A", "B", "C", "D"}
	for i := 0; i < 200; i++ {
		// 35 distinct cells generated by rotating offsets, each cell
		// contributes 2 unique tokens out of 70.
		a := "T" + itoa((2*i)%70)
		b := "T" + itoa((2*i+1)%70)
		rows = append(rows, []string{
			categories[i%len(categories)],
			a + "|" + b,
		})
	}
	r := newMockReader([]string{"id", "issuers"}, rows)
	res, err := InferSchemaWithOptions(r, InferOptions{})
	if err != nil {
		t.Fatalf("InferSchemaWithOptions: %v", err)
	}
	got := res.Schema.Field("issuers").Type
	if got.IsSet() {
		t.Errorf("overflowing token cardinality wrongly classified as %s; want categorical_*", got)
	}
}

func TestInfer_AvgCardinalityOneRejectsSet(t *testing.T) {
	// Every cell has exactly one token; delimiter is absent. The
	// probe never fires — column should be categorical.
	rows := make([][]string, 0, minSampleRows)
	choices := []string{"VISA", "MC", "AMEX"}
	for i := 0; i < minSampleRows; i++ {
		rows = append(rows, []string{itoa(i), choices[i%len(choices)]})
	}
	r := newMockReader([]string{"id", "issuers"}, rows)
	res, err := InferSchemaWithOptions(r, InferOptions{})
	if err != nil {
		t.Fatalf("InferSchemaWithOptions: %v", err)
	}
	got := res.Schema.Field("issuers").Type
	if got.IsSet() {
		t.Errorf("single-token cells wrongly classified as %s; want categorical_*", got)
	}
}

func TestInfer_ForceTypeOverridesInference(t *testing.T) {
	// Single-token sample that would normally land as categorical;
	// force_type pins it to set_u8.
	rows := make([][]string, 0, minSampleRows)
	choices := []string{"VISA", "MC"}
	for i := 0; i < minSampleRows; i++ {
		rows = append(rows, []string{itoa(i), choices[i%len(choices)]})
	}
	r := newMockReader([]string{"id", "issuers"}, rows)
	res, err := InferSchemaWithOptions(r, InferOptions{
		ColumnTypeOverrides: map[string]encoding.FieldType{
			"issuers": encoding.FieldTypeSetU16,
		},
	})
	if err != nil {
		t.Fatalf("InferSchemaWithOptions: %v", err)
	}
	if got := res.Schema.Field("issuers").Type; got != encoding.FieldTypeSetU16 {
		t.Errorf("override type = %s, want set_u16", got)
	}
	if d := res.Delimiters["issuers"]; d == "" {
		t.Errorf("override path must populate delimiter (default %q), got empty", DefaultSetDelimiter)
	}
}

func TestInfer_SetMinPctRespectsCustom(t *testing.T) {
	// Same data as the low-frequency case, but raise the threshold
	// down to 5% so the column lands as set.
	rows := make([][]string, 0, 60)
	for i := 0; i < 10; i++ {
		rows = append(rows, []string{itoa(i), "VISA|MC"})
	}
	for i := 10; i < 60; i++ {
		rows = append(rows, []string{itoa(i), "VISA"})
	}
	r := newMockReader([]string{"id", "issuers"}, rows)
	res, err := InferSchemaWithOptions(r, InferOptions{SetInferenceMinPct: 5})
	if err != nil {
		t.Fatalf("InferSchemaWithOptions: %v", err)
	}
	got := res.Schema.Field("issuers").Type
	if !got.IsSet() {
		t.Errorf("custom min_pct=5 must classify column as set_*, got %s", got)
	}
}

func TestConvertValue_SetU8(t *testing.T) {
	dict := encoding.NewDictionary()
	for _, v := range []string{"VISA", "MC", "AMEX", "DISC"} {
		if _, err := dict.Add(v); err != nil {
			t.Fatalf("dict.Add: %v", err)
		}
	}
	cases := []struct {
		raw  string
		want uint64
	}{
		{"VISA|MC", 0b0011},
		{"AMEX", 0b0100},
		{"AMEX|VISA", 0b0101},
		{"DISC|MC|VISA", 0b1011},
		{"", 0}, // empty cell → empty mask
	}
	for _, c := range cases {
		got, err := convertValue(c.raw, encoding.FieldTypeSetU8, dict, "|")
		if err != nil {
			t.Errorf("convertValue %q: %v", c.raw, err)
			continue
		}
		if got != c.want {
			t.Errorf("convertValue %q = 0b%b, want 0b%b", c.raw, got, c.want)
		}
	}
}

func TestConvertValue_SetU8_OverflowEmitsTypedError(t *testing.T) {
	dict := encoding.NewDictionary()
	// Push 8 tokens — set_u8 capacity is exactly 8. The 9th token
	// must trip PULSE_IMPORT_SET_OVERFLOW.
	for i := 0; i < 8; i++ {
		if _, err := dict.Add("T" + itoa(i)); err != nil {
			t.Fatalf("dict.Add: %v", err)
		}
	}
	_, err := convertValue("T8", encoding.FieldTypeSetU8, dict, "|")
	if err == nil {
		t.Fatal("expected overflow error")
	}
	if !strings.Contains(err.Error(), "PULSE_IMPORT_SET_OVERFLOW") &&
		!strings.Contains(err.Error(), "overflowed") {
		t.Errorf("error = %v, want PULSE_IMPORT_SET_OVERFLOW", err)
	}
}
