# R p.adjust reference for the multiple-comparison correction core
# (multiplicity E1-S1). Never run by CI: the generated Go file is the
# oracle. Base R only (stats::p.adjust); refuses any R but 4.6.1.
#
# Usage (from this directory):
#   Rscript gen_padjust_reference.R
#   gofmt -w ../../reference_values_test.go
#
# Writes ../../reference_values_test.go. Methods: R "bonferroni",
# "holm", "BH", "BY", "none" -> Pulse bonferroni, holm, bh, by, none.
# NA (written as math.NaN() in Go) is dropped from n by p.adjust and
# returned in place, which is the contract the Go core mirrors.
want <- "4.6.1"
have <- sprintf("%s.%s", R.version$major, R.version$minor)
if (have != want) stop(sprintf("R %s required, found %s", want, have))

out_path <- file.path("..", "..", "reference_values_test.go")

methods <- c(bonferroni = "bonferroni", holm = "holm", bh = "BH",
             by = "BY", none = "none")

set.seed(20261005)
large <- c(runif(450), runif(40) * 1e-3, runif(10) * 1e-8)
large_ties <- round(runif(300), 2)

cases <- list(
  list(name = "empty", p = numeric(0)),
  list(name = "single", p = c(0.03)),
  list(name = "single_with_nan", p = c(NA, 0.03, NA)),
  list(name = "all_nan", p = c(NA, NA, NA)),
  list(name = "two", p = c(0.04, 0.01)),
  list(name = "distinct_sorted", p = c(0.001, 0.008, 0.039, 0.041, 0.042, 0.06, 0.074, 0.205, 0.212, 0.216)),
  list(name = "distinct_unsorted", p = c(0.205, 0.001, 0.074, 0.039, 0.216, 0.008, 0.042, 0.212, 0.06, 0.041)),
  list(name = "ties", p = c(0.02, 0.01, 0.02, 0.03, 0.01, 0.02)),
  list(name = "all_equal", p = c(0.04, 0.04, 0.04, 0.04)),
  list(name = "nan_interspersed", p = c(0.01, NA, 0.04, 0.03, NA, 0.005, 0.2)),
  list(name = "zero_and_one", p = c(0, 1, 0.5, 0, 1, 0.02)),
  list(name = "capped", p = c(0.3, 0.6, 0.9, 0.45, 0.8)),
  list(name = "tiny", p = c(1e-300, 5e-200, 1e-16, 0.5)),
  list(name = "non_monotone_step", p = c(0.01, 0.011, 0.012, 0.9, 0.013, 0.014)),
  list(name = "large_m", p = large),
  list(name = "large_m_ties", p = large_ties)
)

fmt <- function(v) {
  if (is.na(v)) return("math.NaN()")
  s <- sprintf("%.17g", v)
  s
}
vec <- function(x) {
  if (length(x) == 0) return("[]float64{}")
  paste0("[]float64{", paste(vapply(x, fmt, ""), collapse = ", "), "}")
}

lines <- c(
  "// Code generated by testdata/padjust_reference/gen_padjust_reference.R; DO NOT EDIT.",
  "",
  "package multiplicity",
  "",
  "import \"math\"",
  "",
  "// padjustRefProvenance records the generating toolchain.",
  sprintf("const padjustRefProvenance = \"R %s, stats::p.adjust\"", have),
  "",
  "// padjustRefCases pins Adjust to R p.adjust, one row per input vector.",
  "var padjustRefCases = []padjustRefCase{"
)
for (cs in cases) {
  lines <- c(lines, "\t{", sprintf("\t\tname: %s,", deparse(cs$name)),
             sprintf("\t\tp: %s,", vec(cs$p)), "\t\twant: map[Method][]float64{")
  for (m in names(methods)) {
    adj <- p.adjust(cs$p, method = methods[[m]])
    lines <- c(lines, sprintf("\t\t\t%s: %s,", deparse(m), vec(adj)))
  }
  lines <- c(lines, "\t\t},", "\t},")
}
lines <- c(lines, "}")
writeLines(lines, out_path)
cat(sprintf("wrote %s (%d cases)\n", out_path, length(cases)))
