package descriptor

import "github.com/frankbardon/pulse/types"

// alphaParam is the shared significance-level parameter used by every
// statistical test. The wire shape lives on the top-level Test struct
// (not in Params), but it is the most-asked parameter so we surface it
// in the manifest entry alongside Params for ergonomics.
var alphaParam = Param{
	Name:        "alpha",
	Type:        "float",
	Required:    false,
	Default:     0.05,
	Description: "Significance level in (0, 1); RejectNull is true when PValue < alpha.",
}

// testCapabilities returns the metadata for every entry in
// types.AllTestTypes(). Order is irrelevant; manifest assembly sorts by
// Name.
func testCapabilities() []TestMeta {
	return []TestMeta{
		{
			Name:        string(types.TEST_T),
			Family:      string(types.TEST_T),
			Tier:        1,
			Description: "One-sample or two-sample Welch t-test on a numeric Field; SplitBy switches to the two-sample variant.",
			Streamable:  types.TEST_T.Streamable(),
			Params: []Param{
				alphaParam,
				{Name: "mu", Type: "float", Required: false, Default: 0.0, Description: "Hypothesized mean for the one-sample variant (ignored when SplitBy is set)."},
			},
			Requires: []string{"Field"},
		},
		{
			Name:        string(types.TEST_WELCH),
			Family:      string(types.TEST_WELCH),
			Tier:        1,
			Description: "Explicit two-sample Welch t-test alias; identical to TEST_T with SplitBy.",
			Streamable:  types.TEST_WELCH.Streamable(),
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "SplitBy"},
		},
		{
			Name:        string(types.TEST_CHISQ),
			Family:      string(types.TEST_CHISQ),
			Tier:        1,
			Description: "Chi-square independence test on a 2D Rows×Cols contingency table.",
			Streamable:  types.TEST_CHISQ.Streamable(),
			Params:      []Param{alphaParam},
			Requires:    []string{"Rows", "Cols"},
		},
		{
			Name:        string(types.TEST_ANOVA_F),
			Family:      string(types.TEST_ANOVA_F),
			Tier:        1,
			Description: "One-way ANOVA F-test comparing Field means across the categorical SplitBy partition.",
			Streamable:  types.TEST_ANOVA_F.Streamable(),
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "SplitBy"},
		},
		{
			Name:        string(types.TEST_KS),
			Family:      string(types.TEST_KS),
			Tier:        1,
			Description: "Kolmogorov-Smirnov two-sample distribution test on Field partitioned by SplitBy.",
			Streamable:  types.TEST_KS.Streamable(),
			Params: []Param{
				alphaParam,
				{Name: "alternative", Type: "enum", Required: false, Default: "two-sided", EnumValues: []string{"greater", "less", "two-sided"}, Description: "One- or two-sided test."},
			},
			Requires: []string{"Field", "SplitBy"},
		},
		{
			Name:        string(types.TEST_PAIRED_T),
			Family:      string(types.TEST_PAIRED_T),
			Tier:        1,
			Description: "Paired-sample t-test on the per-row difference d = Field − Field2.",
			Streamable:  types.TEST_PAIRED_T.Streamable(),
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "Field2"},
		},
		{
			Name:        string(types.TEST_PROP_Z),
			Family:      string(types.TEST_PROP_Z),
			Tier:        1,
			Description: "Two-proportion z-test on the success rate of Field across two SplitBy groups.",
			Streamable:  types.TEST_PROP_Z.Streamable(),
			Params: []Param{
				alphaParam,
				{Name: "success", Type: "string", Required: true, Description: "Dictionary value of Field treated as a success."},
			},
			Requires: []string{"Field", "SplitBy"},
		},
		{
			Name:        string(types.TEST_PEARSON_R),
			Family:      string(types.TEST_PEARSON_R),
			Tier:        1,
			Description: "Parametric Pearson correlation between Field and Field2; reports r and a t-test p-value.",
			Streamable:  types.TEST_PEARSON_R.Streamable(),
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "Field2"},
		},
		{
			Name:        string(types.TEST_MANN_WHITNEY_U),
			Family:      string(types.TEST_MANN_WHITNEY_U),
			Tier:        1,
			Description: "Nonparametric two-sample location test; buffered tie-corrected rank sum.",
			Streamable:  types.TEST_MANN_WHITNEY_U.Streamable(),
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "SplitBy"},
		},
		{
			Name:        string(types.TEST_WILCOXON_SR),
			Family:      string(types.TEST_WILCOXON_SR),
			Tier:        1,
			Description: "Wilcoxon signed-rank test on per-row d = Field − Field2; buffered tie-corrected sign-rank sum.",
			Streamable:  types.TEST_WILCOXON_SR.Streamable(),
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "Field2"},
		},
		{
			Name:        string(types.TEST_KRUSKAL_WALLIS),
			Family:      string(types.TEST_KRUSKAL_WALLIS),
			Tier:        1,
			Description: "Nonparametric k-group location test; ANOVA-like rank sums under tie correction.",
			Streamable:  types.TEST_KRUSKAL_WALLIS.Streamable(),
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "SplitBy"},
		},
		{
			Name:        string(types.TEST_SPEARMAN_R),
			Family:      string(types.TEST_SPEARMAN_R),
			Tier:        1,
			Description: "Rank-based correlation between Field and Field2 (monotonic association).",
			Streamable:  types.TEST_SPEARMAN_R.Streamable(),
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "Field2"},
		},
		{
			Name:        string(types.TEST_KENDALL_TAU),
			Family:      string(types.TEST_KENDALL_TAU),
			Tier:        1,
			Description: "Concordance-based correlation between Field and Field2; buffered O(n²) pair count.",
			Streamable:  types.TEST_KENDALL_TAU.Streamable(),
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "Field2"},
		},
		{
			Name:        string(types.TEST_ANOVA_WELCH),
			Family:      string(types.TEST_ANOVA_WELCH),
			Tier:        1,
			Description: "Heteroscedasticity-robust one-way ANOVA with Welch-Satterthwaite df correction.",
			Streamable:  types.TEST_ANOVA_WELCH.Streamable(),
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "SplitBy"},
		},
		{
			Name:        string(types.TEST_ANOVA_RM),
			Family:      string(types.TEST_ANOVA_RM),
			Tier:        1,
			Description: "Repeated-measures one-way ANOVA; rows pivoted on SubjectField × SplitBy condition.",
			Streamable:  types.TEST_ANOVA_RM.Streamable(),
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "SplitBy", "SubjectField"},
		},
		{
			Name:        string(types.TEST_BROWN_FORSYTHE),
			Family:      string(types.TEST_BROWN_FORSYTHE),
			Tier:        1,
			Description: "Homogeneity-of-variance test; one-way ANOVA on absolute deviations from per-group medians.",
			Streamable:  types.TEST_BROWN_FORSYTHE.Streamable(),
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "SplitBy"},
		},
		{
			Name:        string(types.TEST_FISHER_EXACT),
			Family:      string(types.TEST_FISHER_EXACT),
			Tier:        1,
			Description: "Exact two-sided p-value for a 2×2 Rows×Cols contingency table; small-sample CHISQ alternative.",
			Streamable:  types.TEST_FISHER_EXACT.Streamable(),
			Params:      []Param{alphaParam},
			Requires:    []string{"Rows", "Cols"},
		},
		{
			Name:        string(types.TEST_SHAPIRO_WILK),
			Family:      string(types.TEST_SHAPIRO_WILK),
			Tier:        1,
			Description: "Shapiro-Wilk normality test on Field; runs per-group when SplitBy is set (n ≤ 5000).",
			Streamable:  types.TEST_SHAPIRO_WILK.Streamable(),
			Params:      []Param{alphaParam},
			Requires:    []string{"Field"},
		},
		// Tier-2 natives: TREND and TUKEY_HSD are exclusively post-tests.
		{
			Name:        string(types.TEST_TREND),
			Family:      string(types.TEST_TREND),
			Tier:        2,
			Variant:     "mann_kendall",
			Description: "Mann-Kendall trend test on an ordered numeric series; tier-2 over windowed result rows.",
			Streamable:  false,
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "OrderBy"},
		},
		{
			Name:        string(types.TEST_TUKEY_HSD),
			Family:      string(types.TEST_TUKEY_HSD),
			Tier:        2,
			Variant:     "tukey_kramer",
			Description: "Post-hoc pairwise comparison of group means using Tukey's Honestly Significant Difference.",
			Streamable:  false,
			Params: []Param{
				alphaParam,
				{Name: "ms_within", Type: "float", Required: true, Description: "Within-group mean square from a prior ANOVA aggregate."},
				{Name: "df_within", Type: "float", Required: true, Description: "Within-group degrees of freedom from a prior ANOVA aggregate."},
			},
			Requires: []string{"Field", "SplitBy"},
		},
	}
}

// postTestCapabilities returns metadata for the tier-2 post-test variants
// registered in processing/test_post*.go. Each entry has Tier=2 and a
// non-empty Variant; the natively-tier-2 TREND / TUKEY_HSD entries live in
// testCapabilities() above with Tier=2.
func postTestCapabilities() []TestMeta {
	return []TestMeta{
		{
			Name:        string(types.TEST_ANOVA_F) + "/one_way_from_summary",
			Family:      string(types.TEST_ANOVA_F),
			Tier:        2,
			Variant:     "one_way_from_summary",
			Description: "One-way ANOVA on per-group summary statistics (mean, variance, n) materialized by upstream aggregators.",
			Streamable:  false,
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "SplitBy"},
		},
		{
			Name:        string(types.TEST_PEARSON_R) + "/pearson_post",
			Family:      string(types.TEST_PEARSON_R),
			Tier:        2,
			Variant:     "pearson_post",
			Description: "Pearson correlation between two output columns of the result row set.",
			Streamable:  false,
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "Field2"},
		},
		{
			Name:        string(types.TEST_PAIRED_T) + "/paired_two_sided_post",
			Family:      string(types.TEST_PAIRED_T),
			Tier:        2,
			Variant:     "paired_two_sided_post",
			Description: "Paired t-test on the per-row difference of two output columns.",
			Streamable:  false,
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "Field2"},
		},
		{
			Name:        string(types.TEST_SPEARMAN_R) + "/rank_pearson_post",
			Family:      string(types.TEST_SPEARMAN_R),
			Tier:        2,
			Variant:     "rank_pearson_post",
			Description: "Spearman rank correlation between two output columns of the result row set.",
			Streamable:  false,
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "Field2"},
		},
		{
			Name:        string(types.TEST_KENDALL_TAU) + "/tau_b_post",
			Family:      string(types.TEST_KENDALL_TAU),
			Tier:        2,
			Variant:     "tau_b_post",
			Description: "Kendall tau-b correlation between two output columns of the result row set.",
			Streamable:  false,
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "Field2"},
		},
		{
			Name:        string(types.TEST_WILCOXON_SR) + "/asymptotic_post",
			Family:      string(types.TEST_WILCOXON_SR),
			Tier:        2,
			Variant:     "asymptotic_post",
			Description: "Wilcoxon signed-rank test on the per-row difference of two output columns (asymptotic p-value).",
			Streamable:  false,
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "Field2"},
		},
		{
			Name:        string(types.TEST_ANOVA_WELCH) + "/welch_one_way_post",
			Family:      string(types.TEST_ANOVA_WELCH),
			Tier:        2,
			Variant:     "welch_one_way_post",
			Description: "Welch one-way ANOVA on per-group summary statistics materialized by upstream aggregators.",
			Streamable:  false,
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "SplitBy"},
		},
		{
			Name:        string(types.TEST_BROWN_FORSYTHE) + "/median_post",
			Family:      string(types.TEST_BROWN_FORSYTHE),
			Tier:        2,
			Variant:     "median_post",
			Description: "Brown-Forsythe homogeneity-of-variance test on output columns; absolute deviations from medians.",
			Streamable:  false,
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "SplitBy"},
		},
		{
			Name:        string(types.TEST_SHAPIRO_WILK) + "/shapiro_francia_post",
			Family:      string(types.TEST_SHAPIRO_WILK),
			Tier:        2,
			Variant:     "shapiro_francia_post",
			Description: "Shapiro-Francia normality test on an output column (Shapiro-Wilk variant for the post-row set).",
			Streamable:  false,
			Params:      []Param{alphaParam},
			Requires:    []string{"Field"},
		},
		{
			Name:        string(types.TEST_KS) + "/two_sample_post",
			Family:      string(types.TEST_KS),
			Tier:        2,
			Variant:     "two_sample_post",
			Description: "Kolmogorov-Smirnov two-sample test between two output columns of the result row set.",
			Streamable:  false,
			Params:      []Param{alphaParam},
			Requires:    []string{"Field", "Field2"},
		},
	}
}
