package descriptor

import (
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "update golden files")

// compareGolden compares data against the golden file, updating it if -update is set.
func compareGolden(t *testing.T, name string, data []byte) {
	t.Helper()

	goldenPath := filepath.Join("testdata", name)

	if *update {
		// Write the golden file with a hash comment at the end.
		content := appendHash(data)
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatalf("creating testdata dir: %v", err)
		}
		if err := os.WriteFile(goldenPath, content, 0o644); err != nil {
			t.Fatalf("writing golden file %s: %v", goldenPath, err)
		}
		return
	}

	expected, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("reading golden file %s: %v (run with -update to create)", goldenPath, err)
	}

	// Compare data portion (strip hash line).
	expectedData, _ := splitHash(expected)
	if string(data) != string(expectedData) {
		t.Errorf("golden file mismatch for %s.\nGot:\n%s\nWant:\n%s",
			name, string(data), string(expectedData))
	}
}

// appendHash appends a sha256 hash comment line to the data.
func appendHash(data []byte) []byte {
	h := sha256.Sum256(data)
	hashLine := "\n// golden-hash: " + hex.EncodeToString(h[:]) + "\n"
	return append(data, []byte(hashLine)...)
}

// splitHash separates the data portion from the hash line.
func splitHash(content []byte) (data []byte, hash string) {
	s := string(content)
	idx := strings.LastIndex(s, "\n// golden-hash: ")
	if idx < 0 {
		return content, ""
	}
	hashPart := s[idx+len("\n// golden-hash: "):]
	hashPart = strings.TrimSpace(hashPart)
	return []byte(s[:idx]), hashPart
}

// TestGoldensNotHandEdited verifies that all golden files have valid hashes,
// ensuring they were generated by the test framework, not hand-edited.
func TestGoldensNotHandEdited(t *testing.T) {
	entries, err := os.ReadDir("testdata")
	if err != nil {
		if os.IsNotExist(err) {
			t.Skip("testdata directory does not exist")
		}
		t.Fatalf("reading testdata: %v", err)
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}

		path := filepath.Join("testdata", entry.Name())
		content, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("reading %s: %v", path, err)
			continue
		}

		data, storedHash := splitHash(content)
		if storedHash == "" {
			t.Errorf("%s: no golden-hash found (file may have been hand-edited)", entry.Name())
			continue
		}

		computed := sha256.Sum256(data)
		computedHex := hex.EncodeToString(computed[:])
		if computedHex != storedHash {
			t.Errorf("%s: hash mismatch (file may have been hand-edited)\n  stored:   %s\n  computed: %s",
				entry.Name(), storedHash, computedHex)
		}
	}
}
