package synth_test

import (
	"bytes"
	"context"
	"testing"

	"github.com/frankbardon/pulse"
	"github.com/frankbardon/pulse/encoding"
	"github.com/frankbardon/pulse/synth"
	"github.com/spf13/afero"
)

// readNullFlagsForField returns, in file (row) order, whether each record's
// named field is flagged null via the per-record bitmap
// (encoding.RecordReader.ReadRecord consults encoding.BitmapIsNull
// internally to populate its nulls map — see encoding/reader.go). Used to
// distinguish a genuine null (bitmap bit set) from an in-band sentinel
// value that merely happens to look like zero.
func readNullFlagsForField(t *testing.T, data []byte, name string) []bool {
	t.Helper()
	r := bytes.NewReader(data)
	if err := encoding.ReadHeader(r); err != nil {
		t.Fatalf("read header: %v", err)
	}
	schema, err := encoding.ReadSchema(r)
	if err != nil {
		t.Fatalf("read schema: %v", err)
	}
	rr := encoding.NewRecordReader(r, schema)
	values := make(map[string]float64)
	nulls := make(map[string]bool)
	var out []bool
	for {
		delete(nulls, name)
		if err := rr.ReadRecord(values, nulls); err != nil {
			break
		}
		out = append(out, nulls[name])
	}
	return out
}

// FIXTURES MUST MIRROR THIS DERIVATION. The rule layer refuses a
// set_null naming a non-nullable field, so a hand-built fixture that
// sets Nullable without a NullRate (or a NullRate without Nullable)
// describes a spec SpecFromProfile never produces, and a real refusal
// can pass unnoticed against it — the defect FU-23 found in two
// --suggest-rules tests.
//
// Swept at WP-J across every FieldSpec literal in synth/*_test.go (70 of
// them): NO fixture carries the dangerous direction (NullRate > 0 with
// Nullable false — a spec that draws nulls the file cannot record). Ten
// carry the benign one, Nullable true with NullRate 0, and every one is
// a cohort-GENERATOR spec whose nulls come from a rule rather than from
// a rate, or is the nullability refusal's own subject; a profile of the
// cohort each writes has NullRate > 0, so the derived spec is
// consistent. Re-run the sweep when adding a fixture that feeds a
// hand-built Spec to rule validation or to generation.
//
// TestSpecFromProfile_SetsNullableFromObservedNullRate is the narrow unit
// check behind E6-S3: SpecFromProfile must set FieldSpec.Nullable true for
// a field whose profile carries a positive NullRate, and leave it false
// when NullRate is zero (FieldProfile carries no separate declared-nullable
// flag — NullRate > 0 is the exact proxy, since a non-nullable schema field
// can never contribute a counted null).
func TestSpecFromProfile_SetsNullableFromObservedNullRate(t *testing.T) {
	prof := &pulse.Profile{
		RowCount: 100,
		Fields: []synth.FieldProfile{
			{Name: "nullable_score", Type: "f64", NullRate: 0.3,
				Numeric: &synth.NumericProfile{Min: 0, Max: 1, Mean: 0.5, Std: 0.1}},
			{Name: "solid_score", Type: "f64", NullRate: 0,
				Numeric: &synth.NumericProfile{Min: 0, Max: 1, Mean: 0.5, Std: 0.1}},
		},
	}
	spec, _ := synth.SpecFromProfile(prof, 10)
	if len(spec.Fields) != 2 {
		t.Fatalf("expected 2 fields, got %d", len(spec.Fields))
	}
	if !spec.Fields[0].Nullable {
		t.Errorf("nullable_score: FieldSpec.Nullable = false, want true (NullRate = %v)", spec.Fields[0].NullRate)
	}
	if spec.Fields[1].Nullable {
		t.Errorf("solid_score: FieldSpec.Nullable = true, want false (NullRate = %v)", spec.Fields[1].NullRate)
	}
}

// TestAugmentFromProfile_NullableNumericFieldPreservesNullBitmap is the
// non-negotiable acceptance test for E6-S3, run through the actual
// production path (AugmentFromProfile via p.Synth with SourceCohort set —
// not a bare SpecFromProfile+Synth call). A nullable numeric field in the
// source profile must produce newly-generated null rows verifiable via the
// per-record bitmap (encoding.BitmapIsNull, transitively through
// RecordReader), not an in-band 0 sentinel indistinguishable from a real
// zero.
//
// Before the E6-S3 fix, SpecFromProfile never set FieldSpec.Nullable, so
// buildSchema (synth/writer.go) built the profile-derived generation
// schema (genSchema) with Nullable=false for this field even though
// buildSampler still drew "null" samples from NullRate. encodeRow then
// never recorded those draws in genBuf's bitmap (skipped — field not
// Nullable) and wrote the in-band zero sentinel instead, so the
// null-ness was permanently lost before reencodeRecords ever ran —
// buildMergedSchema's `sf.Nullable || gf.Nullable` union (synth/augment.go)
// only fixes the MERGED FILE'S DECLARED schema nullability (via the
// source field's own always-correct Nullable, read straight off the real
// cohort), not the generated partition's actual data, because the
// generated bytes it re-encodes from already have no null information
// left to preserve.
func TestAugmentFromProfile_NullableNumericFieldPreservesNullBitmap(t *testing.T) {
	fs := afero.NewMemMapFs()
	p, err := pulse.New(pulse.Options{FS: fs})
	if err != nil {
		t.Fatalf("pulse.New: %v", err)
	}

	const sourceRows, newRows = 500, 2000
	sourceSpec := &synth.Spec{
		RowCount: sourceRows,
		Fields: []synth.FieldSpec{
			{Name: "score", Type: "f64", Nullable: true, Distribution: synth.DistNormal,
				Params:   map[string]any{"mean": 50.0, "std": 10.0},
				NullRate: 0.3},
		},
	}
	if _, err := p.Synth(context.Background(), sourceSpec, "/source.pulse",
		pulse.SynthOptions{Seed: 1}); err != nil {
		t.Fatalf("source synth: %v", err)
	}

	prof, err := p.Profile(context.Background(), "/source.pulse", pulse.ProfileOptions{IncludeStats: true})
	if err != nil {
		t.Fatalf("profile: %v", err)
	}
	if prof.Fields[0].NullRate <= 0 {
		t.Fatalf("sanity: source profile NullRate = %v, want > 0", prof.Fields[0].NullRate)
	}

	spec, _ := synth.SpecFromProfile(prof, newRows)
	if !spec.Fields[0].Nullable {
		t.Fatalf("SpecFromProfile: score.Nullable = false, want true (source NullRate = %v)", prof.Fields[0].NullRate)
	}

	if _, err := p.Synth(context.Background(), spec, "/augmented.pulse",
		pulse.SynthOptions{Seed: 2, SourceCohort: "/source.pulse"}); err != nil {
		t.Fatalf("augment synth: %v", err)
	}

	data, err := afero.ReadFile(fs, "/augmented.pulse")
	if err != nil {
		t.Fatalf("read augmented: %v", err)
	}
	flags := readNullFlagsForField(t, data, "score")
	if len(flags) != sourceRows+newRows {
		t.Fatalf("total rows = %d, want %d", len(flags), sourceRows+newRows)
	}

	// The copied-source partition (rows [0, sourceRows)) already round-trips
	// correctly before this fix — buildMergedSchema unions in the source
	// field's own true Nullable flag, and reencodeRecords decodes real
	// values/nulls off the actual source bytes. The bug lives entirely in
	// the GENERATED partition (rows [sourceRows, sourceRows+newRows)): this
	// is the part that must now show real, bitmap-flagged nulls.
	generated := flags[sourceRows:]
	nullCount := 0
	for _, isNull := range generated {
		if isNull {
			nullCount++
		}
	}
	if nullCount == 0 {
		t.Fatalf("generated partition (%d rows, requested null_rate 0.3): 0 rows flagged null via the bitmap — "+
			"null samples are being written as an in-band sentinel instead", len(generated))
	}
	frac := float64(nullCount) / float64(len(generated))
	if frac < 0.15 || frac > 0.45 {
		t.Errorf("generated partition null fraction = %.3f, want near 0.30 (requested null_rate)", frac)
	}
}
