package synth

import (
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"

	"github.com/expr-lang/expr"
	"github.com/frankbardon/pulse/encoding"
)

// This file is the profile-time GATING detector: under
// ProfileOptions.SuggestRules (`profile create --suggest-rules <path>`)
// it measures, for every (low-cardinality field, target field) pair,
// P(target null | field = level), and proposes a rule for every field
// whose levels split a target's null rate into ~1 and ~0.
//
// It exists because the rule layer's value is bounded entirely by rule
// COVERAGE, and rules get written from memory. On the motivating cohort
// the analyst supplied exactly one rule; a second and larger one — a
// four-field question block 155x under-represented in generated output —
// was found by accident while verifying something else. With 122 fields
// the set cannot be enumerated by recall, and an unstated rule is
// invisible in the output because EVERY MARGINAL INSIDE IT IS
// INDIVIDUALLY CORRECT. That is the whole failure class: nothing in the
// profile, the fidelity report or the generated cohort looks wrong.
//
// # Proposed, never auto-applied
//
// The output is a FILE the analyst reads, edits and feeds back. A
// detected pattern can be a coincidence of the sample, and a rule
// applied without review is a silent structural claim about the data —
// the exact thing this effort exists to remove. Nothing here touches the
// spec, the profile document or a generated byte: the candidates reach
// the caller on Profile.RuleCandidates, which is `json:"-"`, so a
// capture WITH the flag writes the same profile document as one without
// it (not merely "absent the flag it is byte-identical" — with it, too).
//
// # It finds the STATISTICAL gate, and says so
//
// Detection can only name the field whose levels split the null rate. A
// human knows the SEMANTIC cause, and the two are routinely different
// fields that move together: on the motivating cohort detection finds
// `aware`, while the analyst's own rule is `familiarity == 1` — measured
// as EXACTLY equivalent there (96,326 rows each, zero exceptions either
// way), which is precisely why the proxy is invisible when it is wrong.
// Every candidate therefore carries a note inviting correction rather
// than asserting cause, and the detector never tries to name the cause.
//
// # It rides the existing scan
//
// The per-row hook is two integer loops over already-decoded maps: no
// second pass, no extra byte read, asserted by counting bytes pulled the
// way TestProfileModels_RidesTheExistingScan does
// (TestSuggestRules_RidesTheExistingScan). The `nulls` map the record
// reader fills holds ONLY the null fields, so the inner loop is over the
// row's nulls rather than over every target — on a survey cohort that is
// tens of increments per gate rather than hundreds.
//
// # What it does NOT look for
//
// Co-missing blocks with no single gating field (E3-S2) and exact
// functional dependencies between non-null values (E3-S3). Both write
// into the same file through the same RuleEvidence.Detector
// discriminant. A relationship among non-null VALUES is out of scope
// here by construction: this detector reads null state only.

const (
	// gateHighNullRate and gateLowNullRate are the "~1 and ~0" of the
	// detection rule: a level whose conditional null rate is at or above
	// the first is GATED, at or below the second is OPEN, and anything
	// between them disqualifies the (gate, target) pair entirely.
	//
	// They are tight on purpose. Skip logic is EXACT in the source — a
	// question not asked has no answer, so the conditional rate is 1 and
	// 0 rather than 0.9 and 0.1 — and the tolerance exists for CODING
	// noise (a handful of rows keyed wrong, a partial re-ask, a merged
	// wave) rather than for association. Measured on the motivating
	// cohort the real gate has zero exceptions in 381,324 rows, so it
	// clears 0.98/0.02 with three orders of magnitude to spare.
	//
	// A looser pair would not find more gates; it would find ordinary
	// ASSOCIATION and propose it as structure. A demographic that merely
	// predicts response rate splits 0.9/0.1 on a large cohort, and a
	// rule built from it is APPLIED UNCONDITIONALLY — false on one row
	// in ten, in a file whose whole purpose is to state facts the data
	// obeys. A rule that is wrong a tenth of the time is worse than no
	// rule, because it is now written down.
	//
	// They are constants, not ProfileOptions fields, for the reason
	// minVarianceExplained and minLevelObservations are: a threshold
	// whose purpose is to mean the same thing across cohorts must not be
	// tunable per run, or two captures of the same data disagree about
	// what the data contains. Re-measure before moving them.
	gateHighNullRate = 0.98
	gateLowNullRate  = 0.02

	// minGateLevelSupport is the rows a level needs before its
	// conditional null rate is treated as a measurement rather than an
	// accident.
	//
	// It DELIBERATELY matches MinPairObservations (30) rather than
	// getting its own number, and the reasoning is the opposite of
	// minLevelObservations': that one is separate because "does this
	// level have enough rows for a FREE COEFFICIENT" is a different
	// question from "does this pair have enough co-occurrences for a
	// CORRELATION to mean anything". This one is the SAME question as
	// MinPairObservations' — does this cell have enough observations for
	// its rate to be a measurement — asked of a conditional null rate
	// instead of a correlation, so giving it a second number would fork
	// one tuning into two for no reason. At n = 30 a level whose true
	// rate is one half comes back all-null with probability 2^-30, so 30
	// is ample for the thing being asked.
	//
	// It does NOT suppress. A candidate resting on a thin level still
	// ships, flagged (RuleEvidence.ThinSupport) and warned, because
	// suppressing it hides a finding the analyst is better placed to
	// judge than the threshold is — see gateThinWarning.
	minGateLevelSupport = MinPairObservations

	// maxGateLevels caps the observed cardinality of a gate CANDIDATE.
	//
	// A gate is a branch, and a branch with more than a handful of arms
	// is not skip logic; it is a high-cardinality attribute that happens
	// to correlate with response. The cap is also what keeps the
	// accumulator bounded without a reservoir: levels x targets counters
	// per candidate, so a 16-level cap over 122 targets is under two
	// thousand integers for the widest candidate in the cohort.
	//
	// It is NOT ProfileOptions.TopK. Borrowing that would tie an
	// ADMISSION decision to a DISPLAY cap — --top-k 4 would silently
	// stop finding a five-level gate — and 16 is chosen for its own
	// reason: it is the full range of a u4, so every u4 field in a
	// cohort is considered whole rather than half-considered.
	//
	// Cardinality is only known as the scan runs, so a candidate is
	// ABANDONED the moment it exceeds the cap. That is exact rather than
	// order-dependent: observed cardinality is monotone, so a candidate
	// that exceeds the cap at any row exceeds it at the last one too.
	maxGateLevels = 16

	// maxRuleCandidates bounds the emitted file, strongest-first, with
	// the remainder counted in a warning.
	//
	// A candidate file nobody reads is not an improvement over no file:
	// the analyst's job here is to JUDGE each proposal, and a hundred
	// proposals is a rubber stamp. The bound matches the convention
	// maxThinLevelWarnings and maxResidualRecoveryPairs already set.
	maxRuleCandidates = 20

	// maxThinGateWarnings caps the thin-support warnings, thinnest-first
	// with a counted remainder, the same shape maxThinLevelWarnings uses
	// for the same reason.
	maxThinGateWarnings = 20

	// gateNullLevelLabel is how the null pseudo-level is SPELLED in the
	// evidence. The predicate spells it isnull(field); this is the
	// display form, and it is never compared against a dictionary value
	// (the level key carries an explicit isNull flag instead of a
	// sentinel string, so a category literally named "(null)" cannot
	// collide with it).
	gateNullLevelLabel = "(null)"

	// gatingDetectorName is the RuleEvidence.Detector discriminant for
	// this detector. Later detectors writing into the same file declare
	// their own.
	gatingDetectorName = "gating"
)

// gateLevel addresses one level of a gate candidate. The null
// pseudo-level is a first-class level with its own key rather than a
// sentinel string, so a categorical whose dictionary happens to contain
// the sentinel's spelling cannot silently merge with it.
type gateLevel struct {
	key    string
	isNull bool
}

// gateLevelAcc is the exact online accumulation behind one level: how
// many rows carried it, and how many of those had each target null.
type gateLevelAcc struct {
	n           int
	targetNulls []int
}

// gateCandidateField is one field admitted as a gate CANDIDATE.
type gateCandidateField struct {
	name string
	// categorical drives both the level spelling (a dictionary entry
	// rather than a number) and the predicate form.
	categorical bool
	dict        *encoding.Dictionary
}

// term renders one gated level as an expr predicate term.
//
// A numeric gate is tested through round(), NOT bare ==, and that is the
// single most load-bearing line in the emitted file. The generated row
// holds the sampler's FLOAT and the wire holds the stored integer, so
// `familiarity == 1` fires only on the draws that landed exactly on 1 —
// measured at 1,843 rows where the file shows 2,739. round() reproduces
// the stored value exactly (an integer field is written as
// floor(v + 0.5)), so the predicate selects the rows the file shows.
// Spelling a packed_bool gate the same way costs nothing — its row value
// is already exactly 0.0 or 1.0 — and buys uniformity: an analyst
// editing the file does not have to know which numeric types are safe
// bare.
func (g gateCandidateField) term(lv gateLevel) string {
	switch {
	case lv.isNull:
		return "isnull(" + g.name + ")"
	case g.categorical:
		return g.name + " == " + strconv.Quote(lv.key)
	default:
		return "round(" + g.name + ") == " + lv.key
	}
}

// label renders one level for the evidence block.
func (g gateCandidateField) label(lv gateLevel) string {
	if lv.isNull {
		return gateNullLevelLabel
	}
	return lv.key
}

// gateDetector is the per-row accumulator. It is nil unless
// ProfileOptions.SuggestRules asked for detection AND the cohort has at
// least one candidate gate and one other field, so the per-row cost for
// every existing caller is exactly zero.
type gateDetector struct {
	schema  *encoding.Schema
	gates   []gateCandidateField
	targets []string
	// targetIdx maps a field name to its index in targets, so the
	// per-row loop can walk the record reader's `nulls` map — which
	// holds ONLY the null fields — instead of every target.
	targetIdx map[string]int

	accs       []map[gateLevel]*gateLevelAcc
	levelCount []int
	// over marks a candidate abandoned for exceeding maxGateLevels.
	over []bool

	// nullIdx is the scratch slice of null target indices for the
	// current row, reused across rows so the hook allocates nothing.
	nullIdx []int

	rows int
}

// gateCandidateFields returns the fields admitted as gate candidates, in
// schema order: the LOW-CARDINALITY types — categorical_*, packed_bool
// and u4. That list is the bound on the pair count, and it is a type
// decision rather than a measured one because it has to be made before
// the first row is read.
//
// A wider numeric is deliberately excluded even though a u8 holding
// three distinct values would be a perfectly good gate: admitting it
// means carrying an unbounded level map for every numeric in the cohort
// until the cardinality cap fires, which on a cohort of continuous
// measures is every row of the scan spent proving the obvious.
func gateCandidateFields(schema *encoding.Schema) []gateCandidateField {
	var out []gateCandidateField
	for i := range schema.Fields {
		f := &schema.Fields[i]
		switch {
		case f.Type.IsCategorical():
			if f.Dictionary == nil {
				continue
			}
			out = append(out, gateCandidateField{name: f.Name, categorical: true, dict: f.Dictionary})
		case f.Type == encoding.FieldTypePackedBool, f.Type == encoding.FieldTypeU4:
			out = append(out, gateCandidateField{name: f.Name})
		}
	}
	return out
}

func newGateDetector(schema *encoding.Schema) *gateDetector {
	gates := gateCandidateFields(schema)
	if len(gates) == 0 || len(schema.Fields) < 2 {
		return nil
	}
	d := &gateDetector{
		schema:    schema,
		gates:     gates,
		targetIdx: make(map[string]int, len(schema.Fields)),
	}
	for i := range schema.Fields {
		d.targetIdx[schema.Fields[i].Name] = len(d.targets)
		d.targets = append(d.targets, schema.Fields[i].Name)
	}
	d.accs = make([]map[gateLevel]*gateLevelAcc, len(gates))
	for i := range d.accs {
		d.accs[i] = make(map[gateLevel]*gateLevelAcc, maxGateLevels+1)
	}
	d.levelCount = make([]int, len(gates))
	d.over = make([]bool, len(gates))
	return d
}

// observe folds one already-decoded row into the accumulators. It reads
// the same three maps profileRecords has just filled and pulls no bytes
// of its own.
func (d *gateDetector) observe(values map[string]float64, nulls map[string]bool) {
	d.rows++

	d.nullIdx = d.nullIdx[:0]
	for name := range nulls {
		if idx, ok := d.targetIdx[name]; ok {
			d.nullIdx = append(d.nullIdx, idx)
		}
	}

	for gi := range d.gates {
		if d.over[gi] {
			continue
		}
		g := &d.gates[gi]
		var lv gateLevel
		switch {
		case nulls[g.name]:
			lv = gateLevel{isNull: true}
		case g.categorical:
			// An id the dictionary cannot resolve is treated as absent,
			// exactly as catAcc treats it when building the marginal —
			// so the two sections of one document cannot disagree about
			// which rows a category was observed on.
			name := g.dict.Resolve(uint32(values[g.name]))
			if name == "" {
				lv = gateLevel{isNull: true}
			} else {
				lv = gateLevel{key: name}
			}
		default:
			lv = gateLevel{key: strconv.FormatInt(int64(values[g.name]), 10)}
		}

		acc := d.accs[gi][lv]
		if acc == nil {
			if !lv.isNull && d.levelCount[gi] >= maxGateLevels {
				// Abandon rather than truncate: a partial level map
				// would make every conditional rate below it a rate over
				// an arbitrary subset of the cohort, which is a number
				// that looks like a measurement and is not one.
				d.over[gi] = true
				d.accs[gi] = nil
				continue
			}
			acc = &gateLevelAcc{targetNulls: make([]int, len(d.targets))}
			d.accs[gi][lv] = acc
			if !lv.isNull {
				d.levelCount[gi]++
			}
		}
		acc.n++
		for _, ti := range d.nullIdx {
			acc.targetNulls[ti]++
		}
	}
}

// gateCandidate is one proposal before it becomes a RuleSpec.
type gateCandidate struct {
	gate         gateCandidateField
	gated        []gateLevel
	open         []gateLevel
	targets      []int
	rowsAffected int
	minSupport   int
	maxDeviation float64
	when         string
	evidence     *RuleEvidence
}

// finish turns the accumulators into candidate rules. It runs after the
// scan, for the same reason the model fits do: the classification is a
// property of the whole cohort and does not exist until every row has
// been seen.
func (d *gateDetector) finish(warnings *[]string) []RuleSpec {
	if d == nil || d.rows == 0 {
		return nil
	}

	var abandoned []string
	var cands []gateCandidate
	comissing := 0
	for gi := range d.gates {
		if d.over[gi] {
			abandoned = append(abandoned, d.gates[gi].name)
			continue
		}
		got, skipped := d.candidatesFor(gi)
		cands = append(cands, got...)
		comissing += skipped
	}
	if len(abandoned) > 0 {
		*warnings = append(*warnings, gateAbandonedWarning(abandoned))
	}
	if comissing > 0 {
		*warnings = append(*warnings, gateComissingWarning(comissing))
	}
	if len(cands) == 0 {
		return nil
	}

	// Ranking. Target COUNT leads, then the rows the rule would change:
	// the analyst is reviewing proposals by hand, and the biggest
	// structural claim is the one they most need to see and most need to
	// get right.
	//
	// The `1 - P(gate)` agreement that identified this cohort's gate by
	// hand — the gated share matching 50 fields' captured null_rate to
	// ten digits — is carried as MaxNullRateDeviation and used as the
	// tiebreak, not as the lead signal, and the reason is arithmetic
	// rather than preference: it is IMPLIED by the split test, so every
	// admitted candidate scores well on it. See
	// RuleEvidence.MaxNullRateDeviation.
	sort.Slice(cands, func(i, j int) bool {
		a, b := cands[i], cands[j]
		if len(a.targets) != len(b.targets) {
			return len(a.targets) > len(b.targets)
		}
		if a.rowsAffected != b.rowsAffected {
			return a.rowsAffected > b.rowsAffected
		}
		if a.maxDeviation != b.maxDeviation {
			return a.maxDeviation < b.maxDeviation
		}
		if a.gate.name != b.gate.name {
			return a.gate.name < b.gate.name
		}
		return a.when < b.when
	})

	// Every emitted predicate is compiled against the SAME environment
	// the rule layer validates against, so a candidate that could not be
	// consumed unmodified is dropped here rather than refused by the
	// loader the analyst feeds it to. Sharing rowExprEnv/rowExprOptions
	// is the point: a second hand-rolled environment is exactly the
	// drift that produced issue #258.
	compiles := d.predicateCompiler()

	out := make([]RuleSpec, 0, maxRuleCandidates)
	var thin []gateCandidate
	dropped := 0
	emitted := 0
	for _, c := range cands {
		if err := compiles(c.when); err != nil {
			dropped++
			continue
		}
		if emitted >= maxRuleCandidates {
			emitted++
			continue
		}
		emitted++
		targets := make([]string, 0, len(c.targets))
		for _, ti := range c.targets {
			targets = append(targets, d.targets[ti])
		}
		out = append(out, RuleSpec{When: c.when, SetNull: targets, Evidence: c.evidence})
		if c.evidence.ThinSupport {
			thin = append(thin, c)
		}
	}
	if dropped > 0 {
		*warnings = append(*warnings, gateUncompilableWarning(dropped))
	}
	if emitted > len(out) {
		*warnings = append(*warnings, gateTruncationWarning(emitted-len(out), len(out)))
	}
	appendGateThinWarnings(warnings, thin)
	return out
}

// predicateCompiler returns a checker that compiles a candidate `when`
// against the row environment a rule's `when` is validated against.
func (d *gateDetector) predicateCompiler() func(string) error {
	specs := make([]FieldSpec, 0, len(d.schema.Fields))
	for i := range d.schema.Fields {
		specs = append(specs, FieldSpec{
			Name: d.schema.Fields[i].Name,
			Type: d.schema.Fields[i].Type.String(),
		})
	}
	env, names := rowExprEnv(specs)
	probe := &compiledConstraints{fields: names}
	opts := rowExprOptions(env, names, probe.isnullBuiltin, expr.AsBool())
	return func(src string) error {
		_, err := expr.Compile(src, opts...)
		return err
	}
}

// candidatesFor classifies every target against one gate candidate and
// groups the survivors by the level set that gated them, so a gate whose
// levels gate two different blocks of fields proposes two rules rather
// than one rule that is wrong about both.
func (d *gateDetector) candidatesFor(gi int) ([]gateCandidate, int) {
	g := d.gates[gi]
	levels := d.sortedLevels(gi)
	if len(levels) < 2 {
		// One level cannot split anything: a gate with a single observed
		// value (a one-wave cohort's `wave`) and an entirely-null field
		// both land here.
		return nil, 0
	}

	type group struct {
		gated   []gateLevel
		open    []gateLevel
		targets []int
	}
	groups := map[string]*group{}
	var order []string
	comissing := 0

	for ti, tname := range d.targets {
		if tname == g.name {
			// A field cannot gate itself: P(g null | g = level) is 0 at
			// every value level and 1 at the null pseudo-level, which
			// classifies perfectly and says nothing.
			continue
		}
		gated, open, ok := d.classify(gi, levels, ti)
		if !ok {
			continue
		}
		if gatedIsNullOnly(gated) {
			// The gate is the ABSENCE of the field rather than any of
			// its values: "these fields are missing on the rows where
			// that one is". That is CO-MISSINGNESS between fields, not
			// value gating, and it is a different detector's finding
			// (E3-S2) — this one is about a field whose LEVEL gates.
			//
			// Excluding it is a readability decision with teeth, not
			// tidiness. Every member of an N-field co-missing block
			// gates the other N-1 through its own null pseudo-level, so
			// keeping them turns one finding into N near-identical
			// candidates all ranked just below the real gate — on the
			// motivating cohort's 50-field block that is the entire
			// remainder of a 20-candidate file, and the genuinely
			// interesting second finding (a small block whose gate is no
			// field at all) is buried beneath them. They are COUNTED
			// instead, so the finding is visible without crowding out
			// everything else.
			comissing++
			continue
		}
		key := gateLevelSetKey(g, gated)
		grp := groups[key]
		if grp == nil {
			grp = &group{gated: gated, open: open}
			groups[key] = grp
			order = append(order, key)
		}
		grp.targets = append(grp.targets, ti)
	}
	if len(groups) == 0 {
		return nil, comissing
	}
	sort.Strings(order)

	out := make([]gateCandidate, 0, len(groups))
	for _, key := range order {
		grp := groups[key]
		out = append(out, d.buildCandidate(gi, grp.gated, grp.open, grp.targets))
	}
	return out, comissing
}

// gatedIsNullOnly reports whether the gated side is nothing but the null
// pseudo-level.
func gatedIsNullOnly(gated []gateLevel) bool {
	for _, lv := range gated {
		if !lv.isNull {
			return false
		}
	}
	return len(gated) > 0
}

// classify splits the gate's levels by this target's conditional null
// rate. It returns ok=false the moment a level lands between the two
// thresholds, or when either side ends up empty — a target that is null
// at every level, or at none, has no gate.
func (d *gateDetector) classify(gi int, levels []gateLevel, ti int) (gated, open []gateLevel, ok bool) {
	m := d.accs[gi]
	for _, lv := range levels {
		acc := m[lv]
		rate := float64(acc.targetNulls[ti]) / float64(acc.n)
		switch {
		case rate >= gateHighNullRate:
			gated = append(gated, lv)
		case rate <= gateLowNullRate:
			open = append(open, lv)
		default:
			return nil, nil, false
		}
	}
	if len(gated) == 0 || len(open) == 0 {
		return nil, nil, false
	}
	return gated, open, true
}

// sortedLevels returns the gate's observed levels in a deterministic
// order: numerically for a numeric gate, lexically for a categorical
// one, with the null pseudo-level last.
func (d *gateDetector) sortedLevels(gi int) []gateLevel {
	m := d.accs[gi]
	out := make([]gateLevel, 0, len(m))
	for lv, acc := range m {
		if acc.n == 0 {
			continue
		}
		out = append(out, lv)
	}
	numeric := !d.gates[gi].categorical
	sort.Slice(out, func(i, j int) bool {
		a, b := out[i], out[j]
		if a.isNull != b.isNull {
			return b.isNull
		}
		if numeric {
			av, aerr := strconv.ParseFloat(a.key, 64)
			bv, berr := strconv.ParseFloat(b.key, 64)
			if aerr == nil && berr == nil && av != bv {
				return av < bv
			}
		}
		return a.key < b.key
	})
	return out
}

func gateLevelSetKey(g gateCandidateField, levels []gateLevel) string {
	parts := make([]string, 0, len(levels))
	for _, lv := range levels {
		parts = append(parts, g.label(lv))
	}
	return strings.Join(parts, "\x1f")
}

// buildCandidate assembles one proposal and its evidence.
func (d *gateDetector) buildCandidate(gi int, gated, open []gateLevel, targets []int) gateCandidate {
	g := d.gates[gi]
	m := d.accs[gi]

	terms := make([]string, 0, len(gated))
	for _, lv := range gated {
		terms = append(terms, g.term(lv))
	}

	gatedN, openN := 0, 0
	minSupport := math.MaxInt
	for _, lv := range gated {
		gatedN += m[lv].n
	}
	for _, lv := range open {
		openN += m[lv].n
	}
	for _, lv := range append(append([]gateLevel{}, gated...), open...) {
		if n := m[lv].n; n < minSupport {
			minSupport = n
		}
	}

	ev := &RuleEvidence{
		Detector:        gatingDetectorName,
		Note:            gateCandidateNote(g.name, len(targets)),
		GateField:       g.name,
		RowsObserved:    d.rows,
		RowsAffected:    gatedN,
		GatedShare:      float64(gatedN) / float64(d.rows),
		MinLevelSupport: minSupport,
		ThinSupport:     minSupport < minGateLevelSupport,
	}

	for _, lv := range gated {
		ev.GatedLevels = append(ev.GatedLevels, g.label(lv))
	}
	for _, lv := range open {
		ev.OpenLevels = append(ev.OpenLevels, g.label(lv))
	}

	// Levels, in the gate's own level order rather than gated-then-open,
	// so the block reads like the field.
	for _, lv := range d.sortedLevels(gi) {
		acc := m[lv]
		side := "open"
		for _, gl := range gated {
			if gl == lv {
				side = "gated"
				break
			}
		}
		sum := 0.0
		for _, ti := range targets {
			sum += float64(acc.targetNulls[ti]) / float64(acc.n)
		}
		ev.Levels = append(ev.Levels, RuleEvidenceLevel{
			Level:              g.label(lv),
			Side:               side,
			N:                  acc.n,
			MeanTargetNullRate: sum / float64(len(targets)),
		})
	}

	maxDev := 0.0
	for _, ti := range targets {
		totalNull, gatedNull, openNull := 0, 0, 0
		for _, lv := range d.sortedLevels(gi) {
			totalNull += m[lv].targetNulls[ti]
		}
		for _, lv := range gated {
			gatedNull += m[lv].targetNulls[ti]
		}
		for _, lv := range open {
			openNull += m[lv].targetNulls[ti]
		}
		t := RuleEvidenceTarget{
			Field:    d.targets[ti],
			NullRate: float64(totalNull) / float64(d.rows),
		}
		if gatedN > 0 {
			t.GatedNullRate = float64(gatedNull) / float64(gatedN)
		}
		if openN > 0 {
			t.OpenNullRate = float64(openNull) / float64(openN)
		}
		if dev := math.Abs(t.NullRate - ev.GatedShare); dev > maxDev {
			maxDev = dev
		}
		ev.Targets = append(ev.Targets, t)
	}
	ev.MaxNullRateDeviation = maxDev

	return gateCandidate{
		gate:         g,
		gated:        gated,
		open:         open,
		targets:      targets,
		rowsAffected: gatedN,
		minSupport:   minSupport,
		maxDeviation: maxDev,
		when:         strings.Join(terms, " || "),
		evidence:     ev,
	}
}

func gateCandidateNote(gate string, targets int) string {
	return fmt.Sprintf(
		"measured, not asserted: %q is the field whose levels split these %d target(s) into ~always-null and ~never-null. "+
			"It is the STATISTICAL gate; the SEMANTIC cause may be a different field that moves with it, so read the rates below and correct `when` before use. "+
			"Note also that set_null repairs co-missingness only — each target's own null_rate still fires beneath the gate, raising its marginal null rate above the captured one.",
		gate, targets)
}

func gateAbandonedWarning(fields []string) string {
	sort.Strings(fields)
	shown := fields
	suffix := ""
	if len(shown) > 5 {
		shown = shown[:5]
		suffix = fmt.Sprintf(" (+%d more)", len(fields)-5)
	}
	return fmt.Sprintf(
		"rule suggestion: %d field(s) were not considered as gates — more than %d observed levels%s: %s%s",
		len(fields), maxGateLevels,
		"; a branch with more arms than that is an attribute, not skip logic",
		strings.Join(shown, ", "), suffix)
}

func gateComissingWarning(n int) string {
	return fmt.Sprintf(
		"rule suggestion: %d relationship(s) not proposed — the gate is the ABSENCE of a field rather than one of "+
			"its values, which is co-missingness between fields rather than value gating; every member of a "+
			"co-missing block reports the others this way, so proposing them would restate one finding N times",
		n)
}

func gateUncompilableWarning(n int) string {
	return fmt.Sprintf(
		"rule suggestion: %d candidate(s) dropped — the gate field's name cannot be written as an expression identifier, "+
			"so the proposed `when` would not compile against the row environment", n)
}

func gateTruncationWarning(remaining, kept int) string {
	return fmt.Sprintf(
		"rule suggestion: +%d further candidate(s) not written; the file carries the %d strongest by target count then rows affected",
		remaining, kept)
}

func gateThinWarning(gate string, targets, n int) string {
	return thinSupportWarning("gate level", gate, fmt.Sprintf("%d target(s)", targets), n,
		minGateLevelSupport,
		"the candidate still ships and carries its support; judge it on the rates in its `_evidence`")
}

// appendGateThinWarnings emits the thin-support listing thinnest-first,
// bounded with a counted remainder — the shape maxThinLevelWarnings and
// maxResidualRecoveryPairs already set, and for the same reason: the
// truncated tail is by construction the least severe part of the finding.
func appendGateThinWarnings(warnings *[]string, thin []gateCandidate) {
	if len(thin) == 0 {
		return
	}
	sort.SliceStable(thin, func(i, j int) bool { return thin[i].minSupport < thin[j].minSupport })
	shown := thin
	if len(shown) > maxThinGateWarnings {
		shown = shown[:maxThinGateWarnings]
	}
	for _, c := range shown {
		*warnings = append(*warnings, gateThinWarning(c.gate.name, len(c.targets), c.minSupport))
	}
	if rest := len(thin) - len(shown); rest > 0 {
		// Worded "further thin gate level(s)" so classifyWarning's
		// generic roll-up arm folds it into the same group as the lines
		// it summarises, rather than needing a row of its own. A cap
		// that split one finding across two counts would defeat the cap.
		*warnings = append(*warnings, fmt.Sprintf(
			"+%d further thin gate level(s) below %d supporting observation(s); "+
				"every candidate still ships and carries its own support", rest, minGateLevelSupport))
	}
}
